"""Workflows as code: generated declarations, workflow list and Code view."""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

import pytest
from fastapi.testclient import TestClient

from api.main import app
from ceg.codegen import task_to_python
from ceg.models.task import CognitiveTask, RepeatSpec, SubTask, TaskConstraint
from ceg.registry import WorkflowDefinition
from ceg.use_cases.demo_pipelines import (
    analyse_ventes_parallele,
    redaction_rapport_iteratif,
    validation_budget_hitl,
)
from ceg.use_cases.multi_agent_supervisor import supervision_strategique
from ceg.use_cases.sales_pipeline import analyse_ventes_alertes

DECLARATIONS: list[WorkflowDefinition] = [
    analyse_ventes_alertes,
    analyse_ventes_parallele,
    redaction_rapport_iteratif,
    validation_budget_hitl,
    supervision_strategique,
]


def _run(code: str) -> dict[str, Any]:
    namespace: dict[str, Any] = {}
    exec(code, namespace)  # noqa: S102 — generated by CEG in the test itself
    return namespace


class TestCodegen:
    @pytest.mark.parametrize("declare", DECLARATIONS, ids=lambda f: f.id)
    def test_generated_code_rebuilds_the_same_declaration(
        self, declare: WorkflowDefinition
    ) -> None:
        task = declare()
        namespace = _run(task_to_python(task))
        assert namespace["task"] == task
        assert [n.id for n in namespace["graph"].nodes] == [
            st.id for st in task.subtasks
        ]

    def test_only_non_default_fields_are_written(self) -> None:
        code = task_to_python(
            CognitiveTask(objective="o", subtasks=[SubTask(id="a", objective="a")])
        )
        assert "requires_approval" not in code
        assert "dependencies" not in code
        assert "SubTask(id='a', objective='a')" in code

    def test_long_strings_are_wrapped_without_changing_them(self) -> None:
        task = CognitiveTask(objective=" ".join(["mot"] * 60))
        code = task_to_python(task)
        assert max(len(line) for line in code.splitlines()) <= 88
        assert _run(code)["task"] == task

    def test_nested_models_are_imported(self) -> None:
        task = CognitiveTask(
            objective="o",
            task_constraints=TaskConstraint(max_cost_usd=0.1),
            subtasks=[
                SubTask(id="a", objective="a"),
                SubTask(
                    id="b",
                    objective="b",
                    dependencies=["a"],
                    repeat=RepeatSpec(back_to="a", while_key="k", max_iterations=2),
                ),
            ],
        )
        code = task_to_python(task)
        assert (
            "from ceg import CognitiveTask, RepeatSpec, SubTask, TaskConstraint, plan"
            in code
        )
        assert _run(code)["task"] == task


@pytest.fixture
def client() -> Iterator[TestClient]:
    with TestClient(app) as c:
        yield c


class TestWorkflowsApi:
    def test_list_shows_every_demo_workflow(self, client: TestClient) -> None:
        workflows = {w["id"]: w for w in client.get("/workflows").json()}
        assert {
            "analyse_ventes_alertes",
            "analyse_ventes_parallele",
            "redaction_rapport_iteratif",
            "multi_agent_supervisor",
            "validation_budget_hitl",
        } <= set(workflows)
        sales = workflows["analyse_ventes_alertes"]
        assert sales["valid"] and sales["steps"] == 5
        assert sales["backends"] == ["langgraph", "python"]
        assert sales["constraints"]["max_cost_usd"] == 0.5

    def test_approval_workflows_only_list_backends_that_support_it(
        self, client: TestClient
    ) -> None:
        hitl = next(
            w
            for w in client.get("/workflows").json()
            if w["id"] == "validation_budget_hitl"
        )
        assert hitl["requires_approval"] is True
        assert hitl["backends"] == ["langgraph"]

    def test_run_history_is_summarised(self, client: TestClient) -> None:
        client.post(
            "/tasks/analyse_ventes_alertes/execute",
            json={"scenario_name": "scenario_a_normal"},
        )
        sales = client.get("/workflows/analyse_ventes_alertes").json()
        assert sales["runs"] >= 1
        assert sales["last_run"]["status"] in ("completed", "failed")
        assert 0.0 <= sales["success_rate"] <= 1.0

    def test_code_view(self, client: TestClient) -> None:
        detail = client.get("/workflows/analyse_ventes_alertes").json()
        # The generated declaration runs and rebuilds what the API executes.
        namespace = _run(detail["python_code"])
        assert namespace["task"].subtasks[-1].run_if == (
            "detect_anomaly.anomalies_found"
        )
        titles = {s["title"]: s for s in detail["sources"]}
        declaration = titles["Déclaration"]
        assert declaration["path"].endswith("use_cases/sales_pipeline.py")
        assert "def analyse_ventes_alertes" in declaration["code"]
        assert declaration["start_line"] > 0
        assert any("class SalesExecutor" in s["code"] for s in detail["sources"])
        assert len(detail["plan"]["nodes"]) == 5

    def test_api_created_task_has_code_but_no_source_file(
        self, client: TestClient
    ) -> None:
        client.post(
            "/tasks",
            json={
                "id": "custom_workflow",
                "objective": "Résumer les tickets",
                "subtasks": [
                    {"id": "read", "objective": "Lire"},
                    {"id": "sum", "objective": "Résumer", "dependencies": ["read"]},
                ],
            },
        )
        detail = client.get("/workflows/custom_workflow").json()
        assert detail["sources"] == []
        assert "SubTask(id='read', objective='Lire')" in detail["python_code"]
        assert _run(detail["python_code"])["task"].objective == "Résumer les tickets"

    def test_unknown_workflow(self, client: TestClient) -> None:
        assert client.get("/workflows/ghost").status_code == 404
